# Generated by Django 4.0.3 on 2022-03-28 04:30

import datetime
from django.db import migrations, models
import promoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0002_alter_coupon_discounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(validators=[promoapp.models.Coupon.end_dates]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[promoapp.models.Coupon.start_dates]),
        ),
    ]
