# Generated by Django 4.0.3 on 2022-03-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
