# Generated by Django 4.0.3 on 2022-03-24 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0003_alter_userdata_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discounttype',
            field=models.CharField(choices=[('flat', 'flat')], default='flat', max_length=7),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_coupen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'please enter uppercase letters & numbers')]),
        ),
    ]
