# Generated by Django 4.0.3 on 2022-03-28 04:34

from django.db import migrations, models
import promoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0003_alter_coupon_end_date_alter_coupon_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(validators=[promoapp.models.Coupon.start_dates]),
        ),
    ]
