# Generated by Django 4.0.3 on 2022-03-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0006_rename_order_user_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='order_user',
        ),
    ]
