# Generated by Django 4.0.3 on 2022-03-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0007_rename_user_order_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_user',
            new_name='user',
        ),
    ]
