# Generated by Django 4.0.3 on 2022-03-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0008_rename_order_user_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discounttype',
            field=models.CharField(choices=[('Flat', 'flat')], default='Flat', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_coupen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_coupen', to='promoapp.coupon'),
        ),
    ]
