# Generated by Django 4.0.3 on 2022-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0010_alter_coupon_discounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discounttype',
            field=models.CharField(choices=[('Flat', 'flat'), ('Percentage', 'percentage')], default='Flat', max_length=10),
        ),
    ]
