# Generated by Django 4.0.3 on 2022-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0012_alter_coupon_discounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='used',
            field=models.IntegerField(),
        ),
    ]
